policies:
  - name: KerasPolicy
    epochs: 200
    max_history: 4
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 4
  - name: FormPolicy